num1=int(input("enter first number:"))
num2=int(input("enter second number:"))
#operator=("+,-,*,/")
# operator=input("enter an operator:")
print("addition:",num1+num2)
print("subtraction:",num1-num2)
print("multiplication:",num1*num2)
print("division:",num1//num2)
print("intridication:",num1:num2)
